---
title: Prediction, Estimation and Inference
author: Peter Elliott
date: "8/19/2018"

slug: "prediction-estimation-inference"
summary: The different types of statistical goals

categories: []
tags: [Statistical Concepts]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In popular culture, statisticians are often thought of as people that like to describe things with numbers. For every event or phenomenon, a statistician can come up with a metric that describes it. From this perspective, a statistic is merely something that sheds a little light. There is relatively little awareness of the idea of statistical modeling, though this in fact is the bulk of what academic statistics is concerned with.

Statistical modeling can be broadly thought of as a way to describe, usually but not necessarly probabilistically, *how* observed data came about. In introductory statistics we often talk about the notion of sampling from a population. We observe certain characteristics in our sample depending on characteristics of the broader population as a whole. When we roll dice, there is no "population" of possible dice rolls but the number that shows is a random process that depends on the number of sides and perhaps some loading that makes it unfair. The purpose of modeling is to go beyond simply describing what we saw to answering questions of actual interest. What kind of person or dice roll will we see next? How common are certain characteristics in the broader population? Are we using fair dice?

I would argue that the goals of statistical modeling tend to fall into one or more of three main buckets: prediction, estimation and inference. These three goals correspond to the questions above. When working with data or interpreting others' analysis, it's important to keep in mind which of these is the underlying goal. These goals are also perhaps where the biggest distinctions between statistics and machine learning lie. While that could be the topic of its own long post (or even a dissertation!), broadly speaking machine learning tends to focus on pure prediction, while statisticians are often more interested in estimation or inference.

## Prediction


## Estimation


## Inference